export const routes = {
    MAIN: '/',
    INCOMMING: '/incomming',
    BETWEEN_ROOM: '/between-room',
    RECORDS: '/records',
    PRICES: '/price',
    LOGIN: '/login',
    ORDER_IN_STOCK: '/orders-in-stock',
    ORDER_BN: '/ordersBN',
    INFO: '/info',
    INFO_BETWEEN: '/info/between',
    INFO_INCOMMING: '/info/incomming',
    INFO_INCOMMING_ADD: '/info/incomming/add',
    FOR_GOOD: '/for-good',
    CHAT: '/chat',
};
