import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/shared/navbar";
import { NavbarMobile } from "@/shared/navbar-mobile";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const revalidate = 300; // НЕ РАБОТАЕТ !!!

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased text-sm lg:text-[18px]`}>
        <div className="block lg:hidden">
          <NavbarMobile />
        </div>
        <div className="lg:flex h-screen">
          <div className="flex-none p-2 w-64 hidden lg:block border-r-2 border-gray-200">
            <Navbar />
          </div>
          <div className="flex-grow p-6">{children}</div>
        </div>
      </body>
    </html>
  );
}
