import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/shared/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const revalidate = 300; // НЕ РАБОТАЕТ !!!

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-sm lg:text-[18px]`}
      >
        <div className="lg:flex h-screen">
          <div className="flex-none p-2 w-64 hidden lg:block border-r-2 border-gray-200">
            <Navbar />
          </div>
          <div className="flex-grow p-6">{children}</div>
        </div>
      </body>
    </html>
  );
}
